[workspace]
edition = "2024"
resolver = "3"

members = [
    "utility",
    "pb_engine",
    "pb_engine2",
    "solve_pb"
]

[profile.dev]
opt-level = 3
lto = true

[prifile.release]
opt-level = 3
lto = true
